    import {ListDataFormat} from './models/list-data-format';

    export const mockData: ListDataFormat[] = [
        {
            date: null,
            listName: 'Competitive Intelligence',
            numOfEntities: 0,
            actions: [true, true, true, true],
            description: ['company 1', 'company 2', 'company 3', 'company 1',
             'company 2', 'company 3', 'company 1', 'company 2', 'company 3',
             'company 1', 'company 2', 'company 3', 'company 1', 'company 2', 'company 3',
             'company 1', 'company 2', 'company 3', 'company 1'],
        },
        {
            date: new Date('2017-01-26'),
            listName: 'My vendor',
            numOfEntities: 0,
            actions: [true, false, false, false],
            description: []
        },
        {
            date: new Date('2017-01-27'),
            listName: 'My Customers',
            numOfEntities: 0,
            actions: [true, false, false, false],
            description: ['company 1', 'company 2', 'company 3'],
        },
        {
            date: null,
            listName: 'Test_30_results',
            numOfEntities: 0,
            actions: [true, false, false, false],
            description: ['company 1', 'company 2', 'company 3'],
        },
        {
            date: new Date('2017-01-28'),
            listName: 'Test_31_results',
            numOfEntities: 0,
            actions: [true, false, false, false],
            description: ['company 1', 'company 2', 'company 3'],
        },
        {
            date: null,
            listName: 'Test_32_results',
            numOfEntities: 0,
            actions: [true, false, false, false],
            description: ['company 1', 'company 2', 'company 3'],
        },
        {
            date: new Date('2017-01-29'),
            listName: 'Test_33_results',
            numOfEntities: 0,
            actions: [true, false, false, false],
            description: ['company 1', 'company 2', 'company 3'],
        },
        {
            date: null,
            listName: 'Test_34_results',
            numOfEntities: 0,
            actions: [true, false, false, false],
            description: ['company 1', 'company 2', 'company 3'],
        },
        {
            date: new Date('2017-01-30'),
            listName: 'results',
            numOfEntities: 0,
            actions: [true, false, false, false],
            description: ['company 1', 'company 2', 'company 3'],
        },
        {
            date: new Date('2017-01-26'),
            listName: 'results1',
            numOfEntities: 0,
            actions: [true, true, true, true],
            description: ['company 1', 'company 2', 'company 3', 'company 1',
             'company 2', 'company 3', 'company 1', 'company 2', 'company 3',
             'company 1', 'company 2', 'company 3', 'company 1', 'company 2', 'company 3'],
        },
        {
            date: new Date('2017-01-25'),
            listName: 'results2',
            numOfEntities: 0,
            actions: [true, false, false, false],
            description: ['company 1', 'company 2', 'company 3'],
        },
        {
            date: null,
            listName: 'Mumbai',
            numOfEntities: 0,
            actions: [false, true, false, false],
            description: ['company 1', 'company 2', 'company 3'],
        },
        {
            date: new Date('2017-01-4'),
            listName: 'Delhi',
            numOfEntities: 0,
            actions: [true, false, false, false],
            description: ['company 1', 'company 2', 'company 3'],
        },
    ];
