    import {ListDataFormat} from './models/list-data-format';

    export const mockData: ListDataFormat[] = [
        {
            date: new Date('2017-01-26'),
            listName: 'Competitive Intelligence',
            actions: [true, true, true, true],
            description: ['Reliance Industries Ltd.', 'Tata Consultancy Services Ltd',
            'HDFC Bank Ltd', 'Hindustan Unilever Ltd', 'Tata Consultancy Services Ltd',
            'HDFC Bank Ltd', 'Hindustan Unilever Ltd', 'Tata Consultancy Services Ltd',
            'HDFC Bank Ltd', 'Hindustan Unilever Ltd', 'Tata Consultancy Services Ltd',
            'HDFC Bank Ltd', 'Hindustan Unilever Ltd', 'Tata Consultancy Services Ltd',
            'HDFC Bank Ltd', 'Hindustan Unilever Ltd', 'Tata Consultancy Services Ltd',
            'HDFC Bank Ltd', 'Hindustan Unilever Ltd'],
        },
        {
            date: new Date('2017-01-26'),
            listName: 'My vendor',
            actions: [true, false, true, false],
            description: []
        },
        {
            date: new Date('2017-01-27'),
            listName: 'My Customers',
            actions: [false, true, true, false],
            description: ['Hindustan Unilever Ltd', 'Tata Consultancy Services Ltd', 'HDFC Bank Ltd', 'Hindustan Unilever Ltd',
             'Hindustan Unilever Ltd', 'Tata Consultancy Services Ltd', 'HDFC Bank Ltd',
              'Hindustan Unilever Ltd', 'Tata Consultancy Services Ltd', 'HDFC Bank Ltd',
             'Hindustan Unilever Ltd', 'Tata Consultancy Services Ltd', 'HDFC Bank Ltd', 'Hindustan Unilever Ltd'],
        },
        {
            date: new Date('2017-01-26'),
            listName: 'Test_30_results',
            actions: [true, true, true, true],
            description: ['Hindustan Unilever Ltd', 'Tata Consultancy Services Ltd', 'HDFC Bank Ltd', 'Hindustan Unilever Ltd',
             'Tata Consultancy Services Ltd', 'HDFC Bank Ltd', 'Hindustan Unilever Ltd', 'Tata Consultancy Services Ltd', 'HDFC Bank Ltd',
             'Hindustan Unilever Ltd', 'Tata Consultancy Services Ltd', 'HDFC Bank Ltd', 'HDFC Bank Ltd',
             'Hindustan Unilever Ltd', 'Tata Consultancy Services Ltd', 'HDFC Bank Ltd', 'Hindustan Unilever Ltd'],
        },
        {
            date: new Date('2017-01-28'),
            listName: 'Test_31_results',
            actions: [true, true, false, false],
            description: [],
        },
        {
            date: new Date('2017-01-26'),
            listName: 'Test_32_results',
            actions: [false, false, true, true],
            description: ['Hindustan Unilever Ltd', 'Tata Consultancy Services Ltd', 'HDFC Bank Ltd'],
        },
        {
            date: new Date('2017-01-29'),
            listName: 'Test_33_results',
            actions: [true, true, true, true],
            description: ['Hindustan Unilever Ltd', 'Tata Consultancy Services Ltd'],
        },
        {
            date: new Date('2017-01-26'),
            listName: 'Test_34_results',
            actions: [true, true, true, true],
            description: ['HDFC Bank Ltd', 'Hindustan Unilever Ltd', 'Tata Consultancy Services Ltd', 'HDFC Bank Ltd',
             'Hindustan Unilever Ltd', 'Tata Consultancy Services Ltd', 'HDFC Bank Ltd', 'HDFC Bank Ltd',
             'Hindustan Unilever Ltd', 'Tata Consultancy Services Ltd', 'HDFC Bank Ltd', 'Hindustan Unilever Ltd'],
        },
        {
            date: new Date('2017-01-30'),
            listName: 'results',
            actions: [true, false, false, false],
            description: ['Hindustan Unilever Ltd', 'Tata Consultancy Services Ltd', 'HDFC Bank Ltd'],
        },
        {
            date: new Date('2017-01-26'),
            listName: 'results1',
            actions: [true, true, true, true],
            description: ['Hindustan Unilever Ltd', 'Tata Consultancy Services Ltd', 'HDFC Bank Ltd', 'Hindustan Unilever Ltd',
             'Tata Consultancy Services Ltd', 'HDFC Bank Ltd', 'Hindustan Unilever Ltd', 'Tata Consultancy Services Ltd', 'HDFC Bank Ltd',
             'Hindustan Unilever Ltd', 'Tata Consultancy Services Ltd', 'HDFC Bank Ltd',
              'Hindustan Unilever Ltd', 'Tata Consultancy Services Ltd', 'HDFC Bank Ltd'],
        },
        {
            date: new Date('2017-01-25'),
            listName: 'results2',
            actions: [true, false, false, false],
            description: ['Hindustan Unilever Ltd', 'Tata Consultancy Services Ltd',
             'HDFC Bank Ltd', 'Hindustan Unilever Ltd', 'Tata Consultancy Services Ltd',
             'HDFC Bank Ltd', 'Hindustan Unilever Ltd', 'Tata Consultancy Services Ltd', 'HDFC Bank Ltd',
             'Hindustan Unilever Ltd', 'Tata Consultancy Services Ltd', 'HDFC Bank Ltd',
              'Hindustan Unilever Ltd', 'Tata Consultancy Services Ltd', 'HDFC Bank Ltd',
             'Hindustan Unilever Ltd', 'Tata Consultancy Services Ltd', 'HDFC Bank Ltd',
              'Hindustan Unilever Ltd', 'Tata Consultancy Services Ltd', 'HDFC Bank Ltd',
             'Hindustan Unilever Ltd', 'Tata Consultancy Services Ltd', 'HDFC Bank Ltd',
              'Hindustan Unilever Ltd', 'Tata Consultancy Services Ltd', 'HDFC Bank Ltd',
             'Hindustan Unilever Ltd', 'Tata Consultancy Services Ltd', 'HDFC Bank Ltd', 'Hindustan Unilever Ltd'],
        },
        {
            date: new Date('2017-01-26'),
            listName: 'Mumbai',
            actions: [false, true, false, false],
            description: ['Hindustan Unilever Ltd', 'Tata Consultancy Services Ltd', 'HDFC Bank Ltd',
            'Hindustan Unilever Ltd', 'Tata Consultancy Services Ltd', 'HDFC Bank Ltd',
             'Hindustan Unilever Ltd', 'Tata Consultancy Services Ltd', 'HDFC Bank Ltd',
            'Hindustan Unilever Ltd', 'Tata Consultancy Services Ltd', 'HDFC Bank Ltd',
             'Hindustan Unilever Ltd', 'Tata Consultancy Services Ltd', 'HDFC Bank Ltd'],
        },
        {
            date: new Date('2017-01-4'),
            listName: 'Delhi',
            actions: [true, false, false, false],
            description: ['Hindustan Unilever Ltd'],
        },
    ];
